name: Debug with Tmate

on:
  # This allows you to run the workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Tmate Session
        uses: mxschmitt/action-tmate@v3
        with:
          # Limit access to the user who triggered the workflow. This is a crucial security step.
          limit-access-to-actor: true

      - name: Display Tmate Connection Info
        if: always()
        run: |
          echo "To connect to the tmate session, use the following command:"
          echo "${{ steps.tmate.outputs.ssh-connection-string }}"
