name: Debug with Tmate (Sleep)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start Tmate Session
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true

      - name: Wait for debug session (30 minutes)
        run: |
          echo "Tmate session is active. Waiting for 30 minutes..."
          sleep 1800 # Waits for 1800 seconds (30 minutes)
        if: always() # Run this step even if the previous one fails to ensure logs are visible
