name: Debug with Upterm

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  debug_job:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Upterm session
        uses: lhotari/action-upterm@v1
        with:
          # This is a crucial security step. It limits access to the user who
          # triggered the workflow run, using their GitHub-registered SSH public key.
          limit-access-to-actor: true

      - name: Your next workflow step
        # Add a "sleep" command to keep the job alive while you debug.
        # Upterm does not have a "detached" mode like tmate, so you must
        # keep the workflow running.
        run: |
          echo "Upterm session is active. Waiting for 30 minutes..."
          sleep 1800
        
      - name: Continue workflow
        run: |
          echo "The workflow continues here after the sleep period."
