name: Debug with Tmate and VNC

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install VNC and Desktop Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y tightvncserver xfce4 xfce4-goodies

      - name: Start VNC Server
        run: |
          VNC_PASSWORD="github-actions-vnc"
          mkdir -p ~/.vnc
          echo "$VNC_PASSWORD" | vncpasswd -f > ~/.vnc/passwd
          chmod 600 ~/.vnc/passwd
          
          tightvncserver :1 -geometry 1280x720 -depth 24 &
          
      - name: Start Tmate Session
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true
      
        if: always()
