name: Tmate Debug

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Tmate Debug Session
        # Use the official tmate action which supports SSH key inputs
        uses: tmate-io/tmate-action@v2
        with:
          # This action uses 'ssh-private-key' as the input name
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Display Tmate Session Info
        if: always()
        run: |
          echo "To connect to the tmate session, use the following command:"
          echo "${{ steps.tmate.outputs.ssh-connection-string }}"
